document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("	<head>");
document.writeln("		<meta charset=\'utf-8\'>");
document.writeln("		<meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("		<meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("		<meta name=\'viewport\' content=\'width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no\' />");
document.writeln("		<meta name=\'apple-mobile-web-app-capable\' content=\'yes\'>");
document.writeln("		<meta name=\'apple-mobile-web-app-status-bar-style\' content=\'black\'>");
document.writeln("		<meta http-equiv=\'Cache-Control\' CONTENT=\'no-cache\'>");
document.writeln("		<title></title>");
document.writeln("		<link rel=\'stylesheet\' href=\'https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css\'>");
document.writeln("		<link rel=\'stylesheet\' href=\'skin/default/layer.css\'>");
document.writeln("		<link rel=\'stylesheet\' type=\'text/css\' href=\'css/reset.css\' />");
document.writeln("		<link rel=\'stylesheet\' type=\'text/css\' href=\'css/header.css\' />");
document.writeln("	</head>");
document.writeln("	<body> ");
document.writeln("		<div class=\'navTitle\'>");
document.writeln("			<ul class=\'clearfix\'>");
document.writeln("				<p class=\'pull-left\'>欢迎来到金师库！</p>");
document.writeln("				<li class=\'pull-left\'><a href=\'http://www.eqidd.com/chuangkeApace/html/EQR.html\' target=\'_blank\'>易企阅</a></li>");
document.writeln("				<li class=\'pull-left\'><a href=\'http://www.jinshiku.cn\' target=\'_blank\'>金师库</a></li>");
document.writeln("				<li class=\'pull-left\'><a href=\'http://www.eqidd.com/yiqiBug/html/EQBuy.html\' target=\'_blank\'>易企购</a></li>");
document.writeln("				<li class=\'pull-left\'><a href=\'http://www.eqidd.com/createrSpace/html/personInfo.html\' target=\'_blank\'>创客空间</a></li>");
document.writeln("				<li class=\'pull-left\'><a href=\'http://www.eqidd.com/qiyeSpace/html/qiyeInfo.html\' target=\'_blank\'>企业空间</a></li>");
document.writeln("				<div class=\'pull-right\'>");
document.writeln("					<li class=\'pull-left loginBtn\'><a id=\'loginBtn\'>登录</a></li>");
document.writeln("					<li class=\'pull-left regBtn\'><a id=\'regBtn\' href=\'http://www.eqidd.com/html/reg.html\' target=\'_blank\'>注册</a></li>");
document.writeln("					<li class=\'pull-left infoBtn\'><a href=\'../createrSpace/html/personInfo.html\' target=\'_blank\' class=\'loginName\'></a></li>");
document.writeln("					<li class=\'pull-left quitOut\'><a href=\'\'>注册</a></li>");
document.writeln("					<li class=\'pull-left download\'><a href=\'http://www.eqidd.com/html/download.html\' target=\'_blank\'>APP");
document.writeln("							下载</a></li>");
document.writeln("				</div>");
document.writeln("			</ul>");
document.writeln("		</div>");
document.writeln("		<div class=\'topArea\'>");
document.writeln("			<div class=\'search contain clearfix\'>");
document.writeln("				<div class=\'searchLeft pull-left\'><img src=\'img/jinshiku.png\' alt=\'\'></div>");
document.writeln("				<div class=\'searchCenter pull-left\'>");
document.writeln("					<div class=\'clearfix\'>");
document.writeln("						<select name=\'\' id=\'selectType\' class=\'pull-left\'>");
document.writeln("							<option value=\'1\'>找讲师</option>");
document.writeln("							<option value=\'2\'>选课程</option>");
document.writeln("							<option value=\'3\'>找需求</option>");
document.writeln("							<option value=\'4\'>品文章</option>");
document.writeln("							<option value=\'5\'>找活动</option>");
document.writeln("						</select>");
document.writeln("						<input type=\'text\' class=\'pull-left\' id=\'inputSearch\'>");
document.writeln("						<button class=\'pull-left\' id=\'searchBtn\'><span class=\'glyphicon glyphicon-search\'></span>搜索</button>");
document.writeln("						<span class=\'pull-left and\'>或</span>");
document.writeln("						<button class=\'pull-left\' id=\'demandBtn\'><span class=\'glyphicon glyphicon-pencil\'></span>发布需求</button>");
document.writeln("					</div>");
document.writeln("					<div class=\'hotSearchDiv\'>");
document.writeln("						<span>热门搜索 : </span>");
document.writeln("						<p class=\'hotWord\'><span>讲师</span><span>课程</span></p>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("				<div class=\'searchRight pull-left clearfix\'>");
document.writeln("					<div class=\'weCahtImg pull-left\'>");
document.writeln("						<img src=\'../image/downQRcode.jpg\' alt=\'\'>");
document.writeln("						<p>微信公众号</p>");
document.writeln("					</div>");
document.writeln("					<div class=\'appDown pull-left\'>");
document.writeln("						<img src=\'../image/adjust.png\' alt=\'\'>");
document.writeln("						<p>APP下载</p>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("	 </body>");
document.writeln("</html> ");
document.writeln("");